import "./globals.css";
import NavBar from "../components/NavBar";
import { Inter } from 'next/font/google';
import { AnimateProvider } from '@/context/context';


const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`antialiased ${inter.className} bg-black`}>
        <AnimateProvider>
          {/* <NavBar /> */}
          {children}
        </AnimateProvider>
      </body>
    </html>
  );
}
